services:
  web:
    image: ghcr.io/ryanradder11/kabbalah-web:latest
    restart: always
    networks:
      web-proxy:
        aliases:
          - kabbalah-web

networks:
  web-proxy:
    external: true
